title: Tesla Fakten
author: Antja Baranek & Felix Reisch
email: info@tesla-fakten.de # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Alle Informationen über die Gigafactory Berlin Brandenburg von Tesla aggregiert, konsolodiert und komprimiert. 
  Keine Füllwörter, keine Meinungen, einfach nur Fakten... natürlich immer mit Quellennachweisen.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.tesla-fakten.de" # the base hostname & protocol for your site, e.g. http://example.com
google_tag_manager: UA-157542757-2
# twitter_username:  # replace with your_twitter_username or comment to remove link from footer
# github_username:  # replace with your_github_username or comment to remove link from footer
# instagram_username:  # replace with your_instagram_username or comment to remove link from footer
# social:
#   name: Your Name
#   links:
#     - https://twitter.com/BenBalter
#     - https://www.facebook.com/ben.balter
#     - https://www.linkedin.com/in/BenBalter
#     - https://plus.google.com/+BenBalter
#     - https://github.com/benbalter
#     - https://keybase.io/benbalter

# disqus:
#   shortname: janczizikow # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
