title: Tesla Fakten
author: Antja Baranek & Felix Reisch
email: info@tesla-fakten.de # email for form submission, you also have to change it in _js/scripts.js
description: > 
  Alle Informationen über die Gigafactory Berlin Brandenburg von Tesla aggregiert, konsolidiert und komprimiert. 
  Keine Füllwörter, keine Meinungen, einfach nur Fakten inklusive Quellennachweisen.
baseurl: "/"
url: "https://www.tesla-fakten.de"
lang: "de-DE"
google_analytics: UA-157542757-2
google_tag_manager: GTM-NDCB3PP
twitter_username: teslafakten
instagram_username: teslafakten 
social:
  name: Tesla Fakten
  links:
    - https://www.twitter.com/teslafakten
    - https://www.instagram.com/teslafakten
    - https://github.com/thefipster/tesla-fakten

keywords:
  - Felix
  - Reisch
  - Antje
  - Baranek
  - Tesla
  - Fakten
  - Gigafactory
  - Berlin
  - Brandenburg
  - Rodung

disqus:
  shortname: tesla-fakten

markdown: kramdown
highlighter: rouge
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-last-modified-at
